### ISSUE TITLE
StrategicMergePatch messes up the ports

### ISSUE THREAD

**Issue by lackhoa** [kubernetes-sigs/kustomize#3513]
StrategicMergePatch messes up the ports, when there are multiple protocols for the same port. 
I tested this on `3.9.2`:

# kustomization.yaml

```
resources:
  - resource.yaml
patches:
  - path: patch.yaml
    target:
      kind: StatefulSet
      name: myapp
```

# resource.yaml

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: myapp
spec:
  template:
    spec:
      containers:
        - name: consul
          image: "hashicorp/consul:1.9.1"
          ports:
            - containerPort: 8500
              name: http
            - containerPort: 8501
              name: https
            - containerPort: 8301
              protocol: "TCP"
              name: serflan-tcp
            - containerPort: 8301
              protocol: "UDP"
              name: serflan-udp
            - containerPort: 8302
              name: serfwan
            - containerPort: 8300
              name: server
            - containerPort: 8600
              name: dns-tcp
              protocol: "TCP"
            - containerPort: 8600
              name: dns-udp
              protocol: "UDP"
```

# patch.yalm

```
kind: StatefulSet
metadata:
  name: myapp
  labels:
    test: label
```

# Result:

```
kustomize build .
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    test: label
  name: myapp
spec:
  template:
    spec:
      containers:
      - image: hashicorp/consul:1.9.1
        name: consul
        ports:
        - containerPort: 8500
          name: http
        - containerPort: 8501
          name: https
        - containerPort: 8301
          name: serflan-udp
          protocol: UDP
        - containerPort: 8301
          name: serflan-udp
          protocol: UDP
        - containerPort: 8302
          name: serfwan
        - containerPort: 8300
          name: server
        - containerPort: 8600
          name: dns-udp
          protocol: UDP
        - containerPort: 8600
          name: dns-udp
          protocol: UDP
```

**Comment by lackhoa** [comment]
@natasha41575 Here you go.

**Comment by monopole** [comment]
Can someone make a PR with a test that reproduces this?

One could add it here 
https://github.com/kubernetes-sigs/kustomize/blob/master/api/krusty/multiplepatch_test.go
or just start a new file.


see https://kubectl.docs.kubernetes.io/contributing/kustomize/bugs/

**Comment by natasha41575** [comment]
@monopole #3514 reproduces the issue, I'm planning to work on a fix this week

**Comment by natasha41575** [comment]
@lackhoa Thank you for filing the isssue, it should be fixed now and will be available in the next release

**Comment by robertdeheer** [comment]
Hello,

I'm still seeing this issue. I tried adding a port and containerPort, but it only adds the containerPort. Adding them both from one patch file causes one of the ports to be duplicated, resulting in three entries in the final array. 

kustomize version
v5.4.3

```
patchesStrategicMerge:
  - patches/requests-limits-patch.yaml
  - patches/deployment-containerport-patch.yaml
  - patches/deployment-port-patch.yaml
 ```

```patches/deployment-containerport-patch.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  template:
    spec:
      containers:
      - name: autofi-app
        ports:
        - containerPort: 8081
          protocol: "TCP"
```

```deployment-port-patch.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  template:
    spec:
      containers:
      - name: autofi-app
        ports:
        - port: 8081
          protocol: "TCP"
```

Thanks for investigating this. 

Rob
