### ISSUE TITLE
Exit code==0 on fail

### ISSUE THREAD

**Issue by johnmarcou** [kubernetes-sigs/kustomize#961]
# What's happen
`Kustomize` returns `exit code 0` even if the build failed.

# What is expected
Get a non-zero exit code, in order to setup a CICD pipeline to fail on `kustomize build` error.

# How to reproduce
```
# mkdir /tmp/reproduce
# cd /tmp/reproduce
# kustomize build
Error: unable to find one of 'kustomization.yaml', 'kustomization.yml' or 'Kustomization' in directory '/private/tmp/reproduce'
# echo $?
0
```

# Version
```
# kustomize version
Version: {KustomizeVersion:v2.0.3 GitCommit:a6f65144121d1955266b0cd836ce954c04122dc8 BuildDate:2019-03-18T22:15:21+00:00 GoOs:darwin GoArch:amd64}
```

**Comment by Liujingfang1** [comment]
This has been fixed on the head. We'll release a new version soon.

**Comment by daviddyball** [comment]
I'm still seeing this issue locally. A bad config still returns `0` when running `kustomize build base/`.

**Comment by Tadimsky** [comment]
I'm also not seeing a non-zero error code when doing something invalid.

For example, 

```
kustomize edit set image foo=gcr.io/bar/foo:dev k8s/kustomization.yaml
```

I would expect this to have a non-zero error code so that my CI fails

**Comment by michael-niemand** [comment]
having the same issue in 3.8.0. This should not be closed I think.

**Comment by tolgaingenc** [comment]
I have the same issue
